<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('games')->insert([
            ['type_id' => 1, 'title' => 'Call of Duty®: Black Ops Cold War - Standard Edition', 'video' => 'https://www.youtube.com/embed/aTS9n_m7TW0', 'price' => 70000, 'photo' => '/asset/cod.jpg', 'description' => 'Black Ops Cold War will drop fans into the depths of the Cold War’s volatile geopolitical battle of the early 1980s. Nothing is ever as it seems in a gripping single-player Campaign, where players will come face-to-face with historical figures and hard truths, as they battle around the globe through iconic locales like East Berlin, Vietnam, Turkey, Soviet KGB headquarters and more.'],
            ['type_id' => 1, 'title' => 'NBA 2K21', 'price' => 65000,  'photo' => '/asset/nba.jpg', 'video' => 'https://www.youtube.com/embed/So_XXvaSr_Q', 'description' => 'NBA 2K21 is the latest title in the world-renowned, best-selling NBA 2K series, delivering an industry-leading sports video game experience. With extensive improvements upon its best-in-class graphics and gameplay, competitive and community online features, and deep, varied game modes, NBA 2K21 offers one-of-a-kind immersion into all facets of NBA basketball and culture - where Everything is Game.'],
            ['type_id' => 1, 'title' => 'Assassins Creed Valhalla', 'price' => 100000, 'video' => 'https://www.youtube.com/embed/gncCKXqjtaE','photo' => '/asset/asscreed.jpg', 'description' => 'In Assassins Creed® Valhalla, become Eivor, a legendary Viking raider on a quest for glory. Explore Englands Dark Ages as you raid your enemies, dual-wield powerful weapons, personalize and grow your clan’s settlement, and build your political power.'],
            ['type_id' => 1, 'title' => 'Mortal Kombat 11 Ultimate', 'price' => 80000, 'video' => 'https://www.youtube.com/embed/7zwQPJmg-Kg','photo' => '/asset/mortal.jpg', 'description' => 'Take control of Earthrealm protectors in 2 acclaimed, time-bending Story Campaigns as they race to stop Kronika from rewinding time & rebooting history. Features the komplete 37-fighter roster, incl. Rain, Mileena & Rambo.'],
            ['type_id' => 1, 'title' => 'Dying Light - Anniversary Edition', 'price' => 90000, 'video' => 'https://www.youtube.com/embed/_yMV1i5ZnvY','photo' => '/asset/dying.jpg', 'description' => 'Take hold of an entire zombie universe with the complete edition of Dying Light. This celebratory package contains the enhanced base game as well as every major expansion and game mode released so far, with a selection of the best DLC items.'],
            ['type_id' => 2, 'title' => 'Minecraft', 'price' => 50000, 'video' => 'https://www.youtube.com/embed/HqllNjR7vl8','photo' => '/asset/minecraft.jpg', 'description' => 'Explore randomly generated worlds and build amazing things from the simplest of homes to the grandest of castles. Play in creative mode with unlimited resources or mine deep into the world in survival mode, crafting weapons and armor to fend off the dangerous mobs.'],
            ['type_id' => 2, 'title' => 'Mario Kart™ 8 Deluxe', 'price' => 30000, 'video' => 'https://www.youtube.com/embed/CjtQZHZc368', 'photo' => '/asset/mario.jpg', 'description' => 'Hit the road with the definitive version of Mario Kart 8 and play anytime, anywhere! Race your friends or battle them in a revised battle mode on new and returning battle courses. Play locally in up to 4-player multiplayer in 1080p while playing in TV Mode. '],
            ['type_id' => 2, 'title' => 'Animal Crossing™: New Horizons', 'price' => 90000, 'video' => 'https://www.youtube.com/embed/AQuucamIYjQ', 'photo' => '/asset/animal.jpg', 'description' => 'Bundle up, it’s sweater weather! Colder weather may be arriving, but luckily, it’s also ushering in warm holiday cheer in the Animal Crossing: New Horizons game for the Nintendo Switch system. Alongside the auburn-colored maple leaves that are beginning to drift down from the trees, islands located in the Northern Hemisphere will be visited by tranquil blankets of snow.'],
            ['type_id' => 2, 'title' => 'The Legend of Zelda™: Breath of the Wild', 'price' => 80000, 'video' => 'https://www.youtube.com/embed/IJnnn0BBj_c', 'photo' => '/asset/zelda.jpg', 'description' => 'Forget everything you know about The Legend of Zelda games. Step into a world of discovery, exploration, and adventure in The Legend of Zelda: Breath of the Wild, a boundary-breaking new game in the acclaimed series. '],
            ['type_id' => 2, 'title' => 'Pokémon Sword', 'price' => 50000, 'video' => 'https://www.youtube.com/embed/2af2KMi-39E', 'photo' => '/asset/pokemon.jpg', 'description' => 'A new generation of Pokémon is coming to the Nintendo Switch™ system. Begin your adventure as a Pokémon Trainer by choosing one of three new partner Pokémon: Grookey, Scorbunny, or Sobble. Then embark on a journey in the new Galar region, where you’ll challenge the troublemakers of Team Yell, while unraveling the mystery behind the Legendary Pokémon Zacian and Zamazenta!'],
            ['type_id' => 3, 'title' => 'RESIDENT EVIL 7 biohazard', 'price' => 60000, 'video' => 'https://www.youtube.com/embed/GpSdPZWmjXI', 'photo' => '/asset/res.jpg', 'description' => 'Fear and isolation seep through the walls of an abandoned southern farmhouse. "7" marks a new beginning for survival horror with the “Isolated View” of the visceral new first-person perspective. Powered by the RE Engine, horror reaches incredible heights of immersion as players enter a terrifyingly new world of fear as they fight to survive.'],
            ['type_id' => 3, 'title' => 'Dead by Daylight Windows', 'price' => 15000, 'video' => 'https://www.youtube.com/embed/ePhHfMiJuPI', 'photo' => '/asset/dead.jpeg', 'description' => 'Death Is Not an Escape. Dead by Daylight is a multiplayer (4vs1) horror game where one player takes on the role of the savage Killer, and the other four players play as Survivors, trying to escape the Killer and avoid being caught, tortured and killed.'],
            ['type_id' => 3, 'title' => 'Microsoft Flight Simulator: Standard', 'price' => 20000, 'video' => 'https://www.youtube.com/embed/GdGB0cv6i8I', 'photo' => '/asset/flight.jpg', 'description' => 'Microsoft Flight Simulator is a new edition of one of the most popular simulation types. From light aircraft to wide-body jets, fly cool planes with incredible detail in a world thats so real.'],
            ['type_id' => 3, 'title' => 'Forza Horizon 4 Standart Edition', 'price' => 10000, 'video' => 'https://www.youtube.com/embed/dGl00hItvbw', 'photo' => '/asset/forza.jpg', 'description' => 'Dynamic seasons change everything at the world’s greatest automotive festival. Go it alone or team up with others to explore beautiful and historic Britain in a shared open world.'],
            ['type_id' => 3, 'title' => 'Final Fantasy XV Windows Edition', 'price' => 30000, 'video' => 'https://www.youtube.com/embed/m8cnVzMw1E8', 'photo' => '/asset/final.jpg', 'description' => 'Includes all of the exciting content released as part of continuous game updates (Chapter 13 alternate route, off-road Regalia customisation, character swap feature and more!).'],

        ]);
    }
}
